# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # Setup keyfile
  boot.initrd.secrets = {
    "/crypto_keyfile.bin" = null;
  };

  # Enable swap on luks
  boot.initrd.luks.devices."luks-043fca33-90e9-4893-a4c4-39c572db102a".device = "/dev/disk/by-uuid/043fca33-90e9-4893-a4c4-39c572db102a";
  boot.initrd.luks.devices."luks-043fca33-90e9-4893-a4c4-39c572db102a".keyFile = "/crypto_keyfile.bin";

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/66c747ea-bd57-456e-8108-c5d2719f65cf";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-96810d35-b9f1-4c05-bb5e-60cb986b72d5".device = "/dev/disk/by-uuid/96810d35-b9f1-4c05-bb5e-60cb986b72d5";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E297-979E";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d0ffa3f7-d725-4951-9f86-6f33cc7e4b35"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp170s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
